site_name: Cloud DevOps Docs
site_url: https://example.com
site_author: Nivas D
theme:
  name: material
  custom_dir: material/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.footer
  icon:
    logo: material/school 
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - abbr
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:  # To keep it simple, each top-level item is a section on the site and has its own dir under `docs`
  - Home:
    - 'Overview': home/overview.md
    - 'Getting Started':
        - 'The Team': home/getting-started/team.md
        - 'What is SlingShot?': home/getting-started/what-is-slingshot.md
        - 'Cloud Organizations': home/getting-started/organizations.md
        - 'The Code Commit Repos': home/getting-started/code-commit.md
        - 'Access': home/getting-started/access.md
        - 'Workstation Setup': home/getting-started/workstation.md
  - AWS:
      - 'Authentication': home/aws/authentication.md
  - Runbooks:
    - 'Cloning the SlingShot Code Commit Repositories': runbooks/clone_code_commit.md
    - 'Requesting new Generic Mailbox and making them available': runbooks/generic_emails.md
extra:
  social:
    - icon: simple/github
      link: https://github.com/nivas-22

copyright: Copyright &copy; 2025 Nivas
