site_name: My Docs
site_url: https://example.com
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.footer
  icon:
    logo: material/school 
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://github.com/nivas-22
    - icon: simple/linkedin
      link: https://linkedin.com/in/iamnivas

copyright: Copyright &copy; 2025 Nivas
