site_name: Cloud DevOps Docs
site_url: https://github.com/nivas-22/clouddevops
site_author: Nivas D
theme:
  name: material
  custom_dir: material/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.footer
  icon:
    logo: material/school 
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

# # Plugins
# plugins:
#   - blog
#   - redirects:
#       redirect_maps:
#         'index.md': docs/overview.md

markdown_extensions:
  - attr_list
  - abbr
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Page tree
nav:  # To keep it simple, each top-level item is a section on the site and has its own dir under `docs`
  - Home: index.md
    
  - AWS:
      - 'iam': home/aws/iam.md

extra:
  social:
    - icon: simple/github
      link: https://github.com/nivas-22

copyright: Copyright &copy; 2025 Nivas
